### PR TITLE
fix(statistics): #242 add api to truncate user queue

### LINKED ISSUE #242: Add API to truncate user queue in statistics

### PR DESCRIPTION
**Pull request by BastienBenard**
## Describe your changes
Add api to truncate user queue

## Checklist tests
Nothing

## Issue ticket number and link
#242 

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

### CODE REVIEW

File: statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java [hunk 1]
```diff
@@ -243,4 +244,13 @@ public void processStudentsStatisticsPrefetch(final HttpServerRequest request) {
                     .onFailure(unused -> renderError(request));
         });
     }
+
+    @Get("user/queue/truncate")
```
Comment (flmartineau) [inline statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java]: Il manque pas un "/" ?

**Review by sjollois — APPROVED** [review]

**Review by flmartineau — APPROVED** [review]

File: statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java (hunk 1 above)
Comment (BastienBenard) [reply statistics-presences/src/main/java/fr/openent/statistics_presences/controller/StatisticsController.java]: Cela marche sans / mais pour respecter ce qui a déjà était fais je vais le rajouter
